Repository homer0/wootils, pull requests merged in 2018-08, with the labels that each got.

#15 Support for HEAD requests on the API client
  documents/shared/APIClient.md
  shared/apiClient.js
  tests/shared/apiClient.test.js
Labels: enhancement, semver:feature

#16 Specify whether to JSON decode an API Client response or not
  shared/apiClient.js
  tests/shared/apiClient.test.js
Labels: bug, enhancement, semver:feature

#17 Set v1.4.0
  package.json
Labels: pr:version, semver:feature

#18 v1.4.0
  documents/shared/APIClient.md
  package.json
  shared/apiClient.js
  tests/shared/apiClient.test.js
Labels: bug, enhancement, pr:next, semver:feature
